version: 1.0
provider:
  name: openfaas
  gateway: http://192.168.1.211:31112
functions:
  client-fn:
    lang: node
    handler: ./client-fn
    image: nomost80/client-fn:latest
  order-fn:
    lang: ruby-http
    handler: ./order-fn
    image: nomost80/order-fn:latest
    environment:
      KAFKA_SERVICE_URL: mercury-kafka.lise-serverless.svc.cluster.local:9092
  payment-fn:
    lang: rust
    handler: ./payment-fn
    image: nomost80/payment-fn:latest
    environment:
      RUST_LOG: debug
    annotations:
      topic: orders
  email-fn:
    lang: ruby
    handler: ./email-fn
    image: email-fn:latest
  todos-fn:
    lang: node10-express-service
    handler: ./todos-fn
    image: todos-fn:latest
