apiVersion: v1
kind: Pod
metadata:
  labels:
    run: curl
  name: curl
  namespace: lise-serverless
spec:
  containers:
    - name: curl
      image: radial/busyboxplus:curl
      imagePullPolicy: IfNotPresent
      resources: {}
      stdin: true
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      tty: true