admin:
  existingSecret: grafana-secrets
  userKey: username
  passwordKey: password

persistence:
  enabled: true
  type: pvc
  storageClassName: nfs-client

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus:9090
        access: proxy
        isDefault: true
      - name: Loki
        type: loki
        url: http://mercury-loki:3100
        access: proxy

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    openfaas:
      gnetId: 3434
      revision: 4
      datasource: Prometheus