---
# Source: grafana/templates/podsecuritypolicy.yaml

apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: mercury-grafana
  namespace: openfaas
  labels:
    app: grafana
    chart: grafana-3.8.11
    heritage: Tiller
    release: mercury
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'docker/default'
    apparmor.security.beta.kubernetes.io/allowedProfileNames: 'runtime/default'
    apparmor.security.beta.kubernetes.io/defaultProfileName:  'runtime/default'
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    # Default set from Docker, without DAC_OVERRIDE or CHOWN
    - FOWNER
    - FSETID
    - KILL
    - SETGID
    - SETUID
    - SETPCAP
    - NET_BIND_SERVICE
    - NET_RAW
    - SYS_CHROOT
    - MKNOD
    - AUDIT_WRITE
    - SETFCAP
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    - 'persistentVolumeClaim'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
  readOnlyRootFilesystem: false

---
# Source: grafana/templates/tests/test-podsecuritypolicy.yaml

apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: mercury-grafana-test
  labels:
    app: grafana
    chart: grafana-3.8.11
    heritage: Tiller
    release: mercury
spec:
  allowPrivilegeEscalation: true
  privileged: false
  hostNetwork: false
  hostIPC: false
  hostPID: false
  fsGroup:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - projected
  - secret

---
# Source: grafana/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mercury-grafana
  namespace: openfaas
  labels:
    app: grafana
    chart: grafana-3.8.11
    release: mercury
    heritage: Tiller
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/data
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning

  datasources.yaml: |
    apiVersion: 1
    datasources:
    - access: proxy
      isDefault: true
      name: Prometheus
      type: prometheus
      url: http://prometheus:9090
    - access: proxy
      name: Loki
      type: loki
      url: http://mercury-loki:3100
    
  dashboardproviders.yaml: |
    apiVersion: 1
    providers:
    - disableDeletion: false
      editable: true
      folder: ""
      name: default
      options:
        path: /var/lib/grafana/dashboards/default
      orgId: 1
      type: file
    
  download_dashboards.sh: |
    #!/usr/bin/env sh
    set -euf
    mkdir -p /var/lib/grafana/dashboards/default
    curl -sk \
    --connect-timeout 60 \
    --max-time 60 \
    -H "Accept: application/json" \
    -H "Content-Type: application/json;charset=UTF-8" \https://grafana.com/api/dashboards/3434/revisions/4/download| sed 's|\"datasource\":[^,]*|\"datasource\": \"Prometheus\"|g'\
    > /var/lib/grafana/dashboards/default/openfaas.json

---
# Source: grafana/templates/dashboards-json-configmap.yaml


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mercury-grafana-dashboards-default
  namespace: openfaas
  labels:
    app: grafana
    chart: grafana-3.8.11
    release: mercury
    heritage: Tiller
    dashboard-provider: default
data:

---
# Source: grafana/templates/tests/test-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mercury-grafana-test
  labels:
    app: mercury-grafana
    chart: "grafana-3.8.11"
    heritage: "Tiller"
    release: "mercury"
data:
  run.sh: |-
    @test "Test Health" {
      url="http://mercury-grafana/api/health"

      code=$(curl -s -o /dev/null -I -w "%{http_code}" $url)
      [ "$code" == "200" ]
    }

---
# Source: grafana/templates/pvc.yaml

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mercury-grafana
  namespace: openfaas
  labels:
    app: grafana
    chart: grafana-3.8.11
    release: mercury
    heritage: Tiller
  finalizers:
    - kubernetes.io/pvc-protection
    
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Gi"
  storageClassName: nfs-client
---
# Source: grafana/templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: grafana
    chart: grafana-3.8.11
    heritage: Tiller
    release: mercury
  name: mercury-grafana
  namespace: openfaas

---
# Source: grafana/templates/tests/test-serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: grafana
    chart: grafana-3.8.11
    heritage: Tiller
    release: mercury
  name: mercury-grafana-test

---
# Source: grafana/templates/clusterrole.yaml

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: grafana
    chart: grafana-3.8.11
    release: mercury
    heritage: Tiller
  name: mercury-grafana-clusterrole
rules: []

---
# Source: grafana/templates/clusterrolebinding.yaml

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mercury-grafana-clusterrolebinding
  labels:
    app: grafana
    chart: grafana-3.8.11
    release: mercury
    heritage: Tiller
subjects:
  - kind: ServiceAccount
    name: mercury-grafana
    namespace: openfaas
roleRef:
  kind: ClusterRole
  name: mercury-grafana-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
# Source: grafana/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: mercury-grafana
  namespace: openfaas
  labels:
    app: grafana
    chart: grafana-3.8.11
    heritage: Tiller
    release: mercury
rules:
- apiGroups:      ['extensions']
  resources:      ['podsecuritypolicies']
  verbs:          ['use']
  resourceNames:  [mercury-grafana]

---
# Source: grafana/templates/tests/test-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mercury-grafana-test
  labels:
    app: grafana
    chart: grafana-3.8.11
    heritage: Tiller
    release: mercury
rules:
- apiGroups:      ['policy']
  resources:      ['podsecuritypolicies']
  verbs:          ['use']
  resourceNames:  [mercury-grafana-test]

---
# Source: grafana/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: mercury-grafana
  namespace: openfaas
  labels:
    app: grafana
    chart: grafana-3.8.11
    heritage: Tiller
    release: mercury
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mercury-grafana
subjects:
- kind: ServiceAccount
  name: mercury-grafana
  namespace: openfaas
---
# Source: grafana/templates/tests/test-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mercury-grafana-test
  labels:
    app: grafana
    chart: grafana-3.8.11
    heritage: Tiller
    release: mercury
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mercury-grafana-test
subjects:
- kind: ServiceAccount
  name: mercury-grafana-test
  namespace: openfaas

---
# Source: grafana/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mercury-grafana
  namespace: openfaas
  labels:
    app: grafana
    chart: grafana-3.8.11
    release: mercury
    heritage: Tiller
spec:
  type: ClusterIP
  ports:
    - name: service
      port: 80
      protocol: TCP
      targetPort: 3000

  selector:
    app: grafana
    release: mercury

---
# Source: grafana/templates/tests/test.yaml
apiVersion: v1
kind: Pod
metadata:
  name: mercury-grafana-test
  labels:
    app: mercury-grafana
    chart: "grafana-3.8.11"
    heritage: "Tiller"
    release: "mercury"
  annotations:
    "helm.sh/hook": test-success
spec:
  serviceAccountName: mercury-grafana-test
  initContainers:
    - name: test-framework
      image: "dduportal/bats:0.4.0"
      command:
      - "bash"
      - "-c"
      - |
        set -ex
        # copy bats to tools dir
        cp -R /usr/local/libexec/ /tools/bats/
      volumeMounts:
      - mountPath: /tools
        name: tools
  containers:
    - name: mercury-test
      image: "dduportal/bats:0.4.0"
      command: ["/tools/bats/bats", "-t", "/tests/run.sh"]
      volumeMounts:
        - mountPath: /tests
          name: tests
          readOnly: true
        - mountPath: /tools
          name: tools
  volumes:
  - name: tests
    configMap:
      name: mercury-grafana-test
  - name: tools
    emptyDir: {}
  restartPolicy: Never

---
# Source: grafana/templates/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: mercury-grafana
  namespace: openfaas
  labels:
    app: grafana
    chart: grafana-3.8.11
    release: mercury
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
      release: mercury
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: grafana
        release: mercury
      annotations:
        checksum/config: 10a220b736a3387da452bd6825bb9b14085613c4ead1b7d30e97f47de53d3d0d
        checksum/dashboards-json-config: 09d9a6c8f6e975598c1d8359d95113ee901e9fcd7f0d1abd1d24c22330dde6d4
        checksum/sc-dashboard-provider-config: 01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b
    spec:
      serviceAccountName: mercury-grafana
      securityContext:
        fsGroup: 472
        runAsUser: 472
        
      initContainers:
        - name: init-chown-data
          image: "busybox:1.30"
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
          command: ["chown", "-R", "472:472", "/var/lib/grafana"]
          resources:
            {}
            
          volumeMounts:
            - name: storage
              mountPath: "/var/lib/grafana"
        - name: download-dashboards
          image: "appropriate/curl:latest"
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh"]
          args: [ "-c", "mkdir -p /var/lib/grafana/dashboards/default && /bin/sh /etc/grafana/download_dashboards.sh" ]
          env:
          volumeMounts:
            - name: config
              mountPath: "/etc/grafana/download_dashboards.sh"
              subPath: download_dashboards.sh
            - name: storage
              mountPath: "/var/lib/grafana"
      containers:
        - name: grafana
          image: "grafana/grafana:6.3.5"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: config
              mountPath: "/etc/grafana/grafana.ini"
              subPath: grafana.ini
            - name: storage
              mountPath: "/var/lib/grafana"
            - name: config
              mountPath: "/etc/grafana/provisioning/datasources/datasources.yaml"
              subPath: datasources.yaml
            - name: config
              mountPath: "/etc/grafana/provisioning/dashboards/dashboardproviders.yaml"
              subPath: dashboardproviders.yaml
          ports:
            - name: service
              containerPort: 80
              protocol: TCP
            - name: grafana
              containerPort: 3000
              protocol: TCP
          env:
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: grafana-secrets
                  key: username
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-secrets
                  key: password
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 60
            timeoutSeconds: 30
            
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            
          resources:
            {}
            
      volumes:
        - name: config
          configMap:
            name: mercury-grafana
        - name: dashboards-default
          configMap:
            name: mercury-grafana-dashboards-default
        - name: storage
          persistentVolumeClaim:
            claimName: mercury-grafana

---
# Source: grafana/templates/configmap-dashboard-provider.yaml


---
# Source: grafana/templates/ingress.yaml


---
# Source: grafana/templates/secret.yaml


