nameOverride: ""
fullnameOverride: ""

persistence:
  storageClass: nfs-client

extraEnvVars:
  - name: KAFKA_CREATE_TOPICS
    value: "orders:1:1"

zookeeper:
  persistence:
    enabled: true
    storageClass: nfs-client

metrics:
  kafka:
    enabled: true