---
# Source: openfaas-loki/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mercury-openfaas-loki
  labels:
    app: openfaas-loki
    chart: openfaas-loki-0.1.0
    release: mercury
    heritage: Tiller
spec:
  type: ClusterIP
  ports:
    - port: 9191
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: openfaas-loki
    release: mercury

---
# Source: openfaas-loki/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mercury-openfaas-loki
  labels:
    app: openfaas-loki
    chart: openfaas-loki-0.1.0
    release: mercury
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openfaas-loki
      release: mercury
  template:
    metadata:
      labels:
        app: openfaas-loki
        release: mercury
    spec:
      containers:
        - name: provider
          image: "theaxer/openfaas-loki:dev"
          imagePullPolicy: Always
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 10001
          env:
            - name: OF_LOKI_URL
              value: "http://mercury-loki:3100"
            - name: OF_LOKI_LOG_LEVEL
              value: "INFO"
            - name: OF_LOKI_TIMEOUT
              value: "30s"
          ports:
            - name: http
              containerPort: 9191
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /-/health
              port: http
              scheme: HTTP
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /-/health
              port: http
              scheme: HTTP
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: 50m
              memory: 120Mi
            

