# Default values for lise-serverless.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

kafka:
  persistence:
    storageClass: nfs-client

  extraEnvVars:
    - name: KAFKA_CREATE_TOPICS
      value: "orders:1:1"

  zookeeper:
    persistence:
      enabled: true
      storageClass: nfs-client

  metrics:
    kafka:
      enabled: true

kafka-connector:
  broker_host: mercury-kafka.lise-serverless.svc.cluster.local
  topics: faas-request,orders

grafana:
  admin:
    existingSecret: grafana-secrets
    userKey: username
    passwordKey: password

  persistence:
    enabled: true
    type: pvc
    storageClassName: nfs-client

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://prometheus:9090
          access: proxy
          isDefault: true

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default

  dashboards:
    default:
      openfaas:
        gnetId: 3434
        revision: 4
        datasource: Prometheus

loki:
  persistence:
    enabled: true
    storageClassName: nfs-client