apiVersion: sources.eventing.knative.dev/v1alpha1
kind: KafkaSource
metadata:
  name: {{ include "payment-function.fullname" . }}-kafka-source
  labels:
{{ include "payment-function.labels" . | indent 4 }}
spec:
  consumerGroup: {{ .Values.kafkaConsumerGroup }}
  # Broker URL. Replace this with the URLs for your kafka cluster,
  # which is in the format of my-cluster-kafka-bootstrap.my-kafka-namespace:9092.
  bootstrapServers: {{ include "kafka.endpoint" . }}
  topics: {{ .Values.kafkaTopics }}
  sink:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: KafkaChannel
    name: {{ include "payment-function.fullname" . }}-kafka-channel