apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: {{ include "payment-function.fullname" . }}-service
  labels:
{{ include "payment-function.labels" . | indent 4 }}
spec:
  template:
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http1
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
          readinessProbe:
            httpGet:
              path: /health
          resources:
            {{- toYaml .Values.resources | nindent 12 }}