apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: cronjob-source-subscription
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: cj-1
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: event-process