apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: lise-microservices-dev
  labels:
    app: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka
          ports:
            - containerPort: 9092
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zk.lise-microservices-dev.svc.cluster.local:2181"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://$(POD_IP):9092"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://:9092"
            - name: KAFKA_CREATE_TOPICS
              value: "orders:1:1"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-svc # https://github.com/wurstmeister/kafka-docker/issues/122#issuecomment-253184494
  namespace: lise-microservices-dev
spec:
  type: ClusterIP
  selector:
    app: kafka
  ports:
    - name: broker-port
      port: 9092
      protocol: TCP