apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  namespace: lise-microservices-dev
  labels:
    app: orders
spec:
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: nomost80/order-service:1.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: orders
  namespace: lise-microservices-dev
spec:
  type: ClusterIP
  selector:
    app: orders
  ports:
    - name: http
      port: 80
      protocol: TCP