apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  namespace: lise-microservices-dev
  labels:
    app: payments
spec:
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: nomost80/payment-service:1.0