apiVersion: apps/v1
kind: Deployment
metadata:
  name: zk
  namespace: lise-microservices-dev
  labels:
    app: zk
spec:
  selector:
    matchLabels:
      app: zk
  template:
    metadata:
      labels:
        app: zk
    spec:
      containers:
        - name: zk
          image: wurstmeister/zookeeper
          ports:
            - containerPort: 2181
---
apiVersion: v1
kind: Service
metadata:
  name: zk
  namespace: lise-microservices-dev
spec:
  type: ClusterIP
  selector:
    app: zk
  ports:
    - name: zk-client-port
      port: 2181
      protocol: TCP