apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lise-serverless.fullname" . }}-grafana-secrets
  labels:
{{ include "lise-serverless.labels" . | indent 4 }}
type: {{ .Values.grafana.secretType }}
data:
  username: {{ .Values.grafana.username }}
  password: {{ .Values.grafana.password }}