apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-grafana-secrets
  labels:
{{ include "lise-serverless.labels" . | indent 4 }}
    app: grafana
type: {{ .Values.grafana.secretType }}
data:
  username: {{ .Values.grafana.username }}
  password: {{ .Values.grafana.password }}