apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: bookinfo
spec:
  targets:
    - name: reviews
  peers:
    - mtls: {}
  origins:
    - jwt:
        issuer: "https://dev-mexo1b5f.eu.auth0.com/"
        jwksUri: "https://dev-mexo1b5f.eu.auth0.com/.well-known/jwks.json"
  principalBinding: USE_ORIGIN