apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "lise-serverful.fullname" . }}-gateway
  labels:
{{ include "lise-serverful.labels" . | indent 4 }}
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
      - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "lise-serverful.fullname" . }}-ingress
  labels:
{{ include "lise-serverful.labels" . | indent 4 }}
spec:
  hosts:
  - "*"
  gateways:
  - {{ include "lise-serverful.fullname" . }}-gateway
  http:
  - match:
    - uri:
        exact: /orders
    route:
    - destination:
        host: {{ include "call-nested" (list . "order-service" "endpoint") }}
        port:
          number: 80