apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: lise-serverless
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tiller
  namespace: lise-serverless
rules:
  - apiGroups: ["", "batch", "extensions", "apps", "networking.istio.io", "serving.knative.dev", "eventing.knative.dev", "messaging.knative.dev", "sources.eventing.knative.dev"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tiller
  namespace: lise-serverless
subjects:
  - kind: ServiceAccount
    name: tiller
    namespace: lise-serverless
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tiller