# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: "lise"
fullnameOverride: "lise"

# Dependencies parameters
kafka:
  persistence:
    enabled: false
  extraEnvVars:
    - name: KAFKA_CREATE_TOPICS
      value: "orders:1:1"
  zookeeper:
    persistence:
      enabled: false