apiVersion: v1
kind: ServiceAccount
metadata:
  name: helm
  namespace: helm-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: helm
rules:
  - apiGroups: [""]
    resources: ["pods/portforward"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "get"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: helm
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: helm
subjects:
  - kind: ServiceAccount
    name: helm
    namespace: helm-system