apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: lise-microservices-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tiller
  namespace: lise-microservices-dev
rules:
  - apiGroups: ["", "batch", "extensions", "apps"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tiller
  namespace: lise-microservices-dev
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: lise-microservices-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tiller